### ISSUE TITLE
Weird ENOENT error

### ISSUE THREAD

**Issue by iamale** [johanbrook/gulp-fontcustom#4]
```
~/SomeProject/app $ gulp icons    
[gulp] Using gulpfile ~/SomeProject/app/gulpfile.js
[gulp] Starting 'icons'...

/home/ale/SomeProject/app/node_modules/gulp-fontcustom/node_modules/child-process-promise/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Can't list "./___tmp___": ENOENT, readdir './___tmp___'
```

Config looks like so (nothing unusual here):

```js
var gulp = require('gulp'),
    fontcustom = require('gulp-fontcustom');

gulp.task('icons', function() {
  return gulp.src("src/icons/*.svg")
    .pipe(fontcustom({
      font_name: 'MaterialIcons'
    }))
    .pipe(gulp.dest("www/icons/"));
});
```

What could have gone wrong?

**Comment by iamale** [comment]
Looks like deleting `.fontcustom-manifest.json` helped around this issue.

It still would be better to pass any error output from fontcustom, since it would have given a hint:

```
error  Couldn't parse `.fontcustom-manifest.json`. Fix any invalid JSON or delete the file to start from scratch.
```

**Comment by pushred** [comment]
Same here, but I don't have a `.fontcustom-manifest.json` file to delete.

**Comment by mr-mig** [comment]
The problem is that there is no error output from `exec`, from fontcustom process run.

**Comment by johanbrook** [comment]
I've merged #8 to `master`, feel free to pull down and verify.

**Comment by JoshuaMorris** [comment]
I'm running into a similar problem and #8 doesn't fix the problem. I still get the error:

`fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '<SNIP>/___tmp___/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Gaze.emit (<SNIP>/node_modules/gaze/lib/gaze.js:135:10)
    at Gaze.<anonymous> (<SNIP>/node_modules/gaze/lib/gaze.js:401:18)
    at Timeout._onTimeout (<SNIP>/node_modules/gaze/lib/gaze.js:427:24)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)`

**Comment by kikar** [comment]
Can you update npm package with fix?

**Comment by johanbrook** [comment]
@kikar Done! https://www.npmjs.com/package/gulp-fontcustom
